### Get all products
GET http://localhost:3000/products

###
GET http://localhost:3000/products/6a153ad015b903abb0afb3cf

### Add a product

POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Keyboard",
  "price": 49.99,
  "quantity": 1
}

### Add a product
PUT http://localhost:3000/products/6a153ad015b903abb0afb3cf
Content-Type: application/json

{
  "name": "Rubber",
  "price": 50,
  "quantity": 1
}

###
PATCH http://localhost:3000/products/6a153ad015b903abb0afb3cf
Content-Type: application/json

{
  "name": "King"
}

###
DELETE http://localhost:3000/products/6a1529ff9ba914d9ae38268a